[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = ['python']

[[plugins]]
repo = 'padawan-php/deoplete-padawan'
depends = ['deoplete.nvim']
on_ft = ['php']

[[plugins]]
repo = 'preservim/tagbar'

